osx_image: xcode10.2
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=InfiniteScroller
cache:
  directories:
  - Carthage
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_deploy:
- carthage archive $FRAMEWORK_NAME
script:
- carthage build --no-skip-current --platform iOS --cache-builds
- pod lib lint
after_deploy:
- pod trunk push
deploy:
  provider: releases
  api_key:
    secure: bQ868OEwqgHL9wFA1idVP5YEWM3E+35h0Xvz5YfvB2D2nh3UxHoK+T3A/Zc2Ssz32GSIMP6TQsdZHwkFPWn79QZMAOvduFKHHK+sZ+9VC7VCMr1BJKn685tBLVeIcZ1zStzAty+5kP3wjye4+hNFaiS3fFu4Sbbgb5Ku3fdpc9DjQCrKJmyXaybPkfp6ZPCCyxvCZVKgPxLzjEej9AAoiJlw8rWM/7rIF3be9hTNHNTDW+6m5MLxvKg5KMz6UQP9nV+m6HaMYg3qZy9M7o7Cr6g2x0HFtwz2SEStRHrIfY0zJ6zidn2x5d6yUkwmLEhqhwStsy0ieTNkh67WfBLNtyXfojmjLMah0gUd79ypgXRbdw+P2LhHTYfox1EP5Hzw/QiD8/nSWecMZ872S/Nwntl3f/6E+GykpmlqMfnnEKNmJnAd2kN7Od7gm4TE63I55tOaqlRs8fBALd/2L4Wp9FxUOb3lEistj8tWVh6n8645hdDUkTRt8N8XuB2pbbczaY0s3t12VOTKjJ6noGn8djDDEb+6eF+ZirlLi5wct4s13yu7qlIoSyG/peQPQwQ9fTnubIpqwHjDomrCefgb2eE24LeTzleURMnIP8jG1Zu83eL0Y44t2Dv3pLLx6igBol0y2BLGsGmgIrYwHxoIRccLZXjMQ8i01gvdHxbKI8o=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: olejnjak/InfiniteScroller
    tags: true
